var questions = [
"draw a flowchart for a computer program to receive two numbers and output their sum.",
"draw a flowchart for a computer program to receive three numbers and store them in memory spaces called a, b, and c as three sides of a triangle and, by using Heron’s formula, calculate and output the area of the triangle.",
"draw a flowchart for a computer program to receive three numerical coefficients of a quadratic equation (store them in memory spaces called a, b, and c) and calculate and output its roots. Write a precondition that assumes coefficients are good enough such that a solution in real number exists.",
"draw a flowchart to receive three numerical coefficients of a quadratic equation and determines if it has two distinct real roots, one root, or no roots in real numbers.",
"draw a flowchart to receive a number and map it to a letter grade based on York standard.",
"assume there is a webpage containing an HTML input of type text and a button. When the button is clicked a function, named Problem06, is called. Draw a flowchart that outputs whether the input is positive or negative until a zero is received. When a zero is received, the button is disabled (so the function cannot be called anymore).",
"by modifying your flowchart above, draw a flowchart to continue receiving numbers and output if they are positive or negative until a zero is entered. When a zero is entered, the program should output how many positive and how many negative numbers have been entered, then it stops.",
"considering the same approach above, draw a flowchart to continue receiving numbers and output if they are divisible by 6 or not until a zero is entered. When a zero is entered, the program should output how many of the entered numbers were divisible by 6, then it stops. IMPORTANT RESTRICTION: you are not allowed to divide the number by 6; therefore, you are not allowed to use the modulus operator (%) over 6 to verify the remainder whether the number is divided by 6.",
"Devise a flowchart to receive a positive number and output each digit separately. For instance, if the input is 692, the program should output 2, 9, 6. Another example, if the number is 135429 the program should out put 9, 2, 4, 5, 3, and 1.",
"Devise a flowchart to receive a positive number and output how many of its digits are equal to 7. For instance, if the input is 772, the program should output 2, because there are two sevens there. Another example, if the input is 14368, the program should output 0.",
"Devise a flowchart to receive a positive number and output sum of its digits. For instance, if the input is 63932, the program should output 23, because 6+3+9+3+2 is 23. Another example, if the input is 23 the program should output 5.",
"Devise a flowchart to receive a positive number and output \"yes\" if it's equal to its reverse; otherwise, output \"no\". For instance, if the input is 63936, the program should output \"yes\", because if you read the digits from left to right or from right to left, it's the same number. But, if the input is 632, the program should output \"no\" because 632 is not the same as 236.",
"Devise an algorithm to receive a positive number, as n, and output n! (n Factorial).",
"Devise an algorithm to input an integer greater than 1, as n, and output the first n values of the Fibonacci sequence. In Fibonacci sequence, the first two values are 0 and 1 and other values are sum of the two values preceding it. For instance, if the input is 4, the program should print 0, 1, 1, 2,. As another example, if the input is 9, the program should output 0, 1, 1, 2, 3, 5, 8, 13, 21,.",
"Devise an algorithm to input a positive integer, n, – and by using XX characters – output the figure below that has n rows and each row k has k pairs of XX. For instance, if input is 5, the figure on the left (and if the input is 12, the figure on the right) should be generated by the program.",
"Devise an algorithm to input 200 numbers and determine how many are positive and how many negative.",
"Devise an algorithm to receive a number and determine if it’s a prime number or not.",
"Devise an algorithm to output 12 characters \“*\”",
"Devise an algorithm to output all prime numbers between 2 and 1000, inclusively.",
"devise a program to output sum of values stored in an array of 100 elements."
];
function checkUncheck1(){
  if (document.getElementById("check1").checked==true) {
     // add a getElementById here to get "flowchart" img and 
     // set the display property of its style to "inline"	 
     document.getElementById("flowchart").style.display="inline";
	 
  }
  else {
     // add a getElementById here to get "flowchart" img and 
     // set the display property of its style to "none"	 
	  document.getElementById("flowchart").style.display="none";
	  
  }
}
function checkUncheck2(){
  if (document.getElementById("check2").checked==true) {
     // add a getElementById here to get "js" img and 
     // set the display property of its style to "inline"	 
     document.getElementById("js").style.display="inline";
	 
  }
  else {
     // add a getElementById here to get "js" img and 
     // set the display property of its style to "none"	 
	  document.getElementById("js").style.display="none";
	  
  }
}
function checkUncheck3(){
   if (document.getElementById("check3").checked==true) {
      // add a getElementById here to get "js" img and 
      // set the display property of its style to "inline"	 
      document.getElementById("another").style.display="inline";
     
   }
   else {
      // add a getElementById here to get "js" img and 
      // set the display property of its style to "none"	 
      document.getElementById("another").style.display="none";
      
   }
}
function buttons(){
   for(i = 1; i <= 40; i++){

      var button = document.createElement("button");
      button.innerHTML = "problem " + i;
      //button.id = "prb" + i;
      button.setAttribute("onclick", "problem("+ i+")");
      document.getElementById("buttons").appendChild(button);
   }

}
function problem(num){
   document.getElementById("problem").innerHTML="<p>" + questions[num-1] + "</p>";
   
   document.getElementById("flowchart").setAttribute("src","images/ex_"+num+".jpg");
   document.getElementById("flowchart").style.display="none";
  
   document.getElementById("js").setAttribute("src","images/html/ex_"+num+".html");
   document.getElementById("js").style.display="none";
   
  // document.getElementById("another").setAttribute("src","images/jujeh/jujeh2.jpg");
  // document.getElementById("another").style.display="none";

   document.getElementById("check1").checked=false;
   document.getElementById("check2").checked=false;
   document.getElementById("check3").checked=false;

}
function zoomIn(){

   document.getElementById("flowchart").style.width="200%";

}
function zoomOut(){

   document.getElementById("flowchart").style.width="100%";

}